# configs/default.yaml
paths:
  raw_video: data/raw/video.mp4
  raw_image: data/raw/image.jpg
  interim_frames: data/interim/frames
  interim_partials: data/interim/partials
  interim_detections: data/interim/detections
  interim_detections_batch: data/interim/detections_batch
  interim_mosaic: data/interim/mosaic.jpg
  interim_homographies: data/interim/homography
  processed_image: data/processed/processed_image.jpg
  p1_result: data/processed/p1_result.jpg
  p2_result: data/processed/p2_result.jpg

video:
  frame_step: 30       # take every 30th frame

detect:
  model: rb_vehicle # {rb_vehicle, YOLO}
  conf: 0.5 # detector confidence treshold
  iou: 0.5
  YOLO:
    weight: yolov8n.pt

stitch:               # do a research on this
  feature: ORB
  reproj_thresh: 4.0
  resize_factor: 0.5
  chunk_size: 5
  mode: SCANS

homography: # currently not connected to the stitcher
  method: RANSAC
  ransac_reproj_thresh: 4.0
  ransac_confidence: 0.99
  min_inliers: 10

postprocess:
  confidence:
    run: true
    conf_min: 0.6

  size_quantiles:
    run: true
    size_low_q: 0.1
    size_high_q: 0.95

  proximity_clustering:
    run: true
    prox_factor: 0.45
    iou_merge: 0.5

  support:
    run: true
    min_support_frames: 4
    min_support_members: 6

  texture_rejection:
    run: true
    texture_min: 40
    inner_shrink: 0.10
    empty_std_max: 15
    empty_edge_max: 0.02
