paths:
  raw: data/raw
  interim_frames: data/interim/frames
  interim_mosaic: data/interim/mosaic.jpg
  interim: data/interim
  processed: data/processed
  processed_image: data/processed/processed_image.jpg
  results: experiments

video:
  frame_step: 5       # take every 5th frame

stitch:
  feature: ORB
  reproj_thresh: 4.0

detect:
  model: yolov8n.pt
  conf: 0.4
  iou: 0.5
