paths:
  raw_video: data/raw/video.mp4
  raw_image: data/raw/image.jpg
  interim_frames: data/interim/frames
  interim_partials: data/interim/partials
  interim_detections: data/interim/detections
  interim_detections_batch: data/interim/detections_batch
  interim_mosaic: data/interim/mosaic.jpg
  interim_homographies: data/interim/homography
  processed_image: data/processed/processed_image.jpg
  results: experiments

video:
  frame_step: 30       # take every 30th frame

stitch:               # do a research on this
  feature: ORB
  reproj_thresh: 4.0
  resize_factor: 0.5
  chunk_size: 5
  timeout: 300
  mode: SCANS

homography: # currently not connected to the stitcher
  method: RANSAC
  ransac_reproj_thresh: 4.0
  ransac_confidence: 0.99
  min_inliers: 10

detect:
  model: rb_vehicle # TODO: detection model picker
  conf: 0.5
  iou: 0.5
  YOLO:
    model: yolov8n.pt

postprocess:
  conf_min: 0.25
  size_low_q: 0.1
  size_high_q: 0.95
  prox_factor: 0.45
  iou_merge: 0.5
  texture_min: 40
  min_support_frames: 4

# mode scans is better for 2d, but for some reason, final stitching on panorama is better?
# mode panorama + chunk_size 5 + frame_step 60 gave best results but one weird partial