paths:
  raw: data/raw
  interim_frames: data/interim/frames
  interim_mosaic: data/interim/mosaic.jpg
  interim: data/interim
  processed: data/processed
  processed_image: data/processed/processed_image.jpg
  results: experiments

video:
  frame_step: 60       # take every 60th frame

stitch:               # do a research on this
  feature: ORB
  reproj_thresh: 4.0
  resize_factor: 0.2
  chunk_size: 3
  timeout: 300
  mode: SCANS


detect:
  model: yolov8n.pt
  conf: 0.5
  iou: 0.5
